### ISSUE TITLE
3.4.6 Analyze Frazier distance uncertainty vs Wieczorek

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-best-practices#1]
Frazier published a method to add 15% to the distance value in a locality with an offset to get the contribution of distance uncertainty. Wieczorek published the method that takes into account the human factor of how localities are recorded (represented in fractions, ultimately). Look at the differences between these and justify a recommendation. SIB Colombia used the former method, so ask why they did that.

**Comment by RicardoOrtizG** [comment]
Hi John!

As was documented in our protocol at that time, one of the reasons was the consistency of uncertainty between larger and short distances, and because is more operative in the process of georeferencing (manual).

Under the older method of uncertainty due to distance (Wieczorek, 2004), for 2 km we had an uncertainty of 1 km with the Wieczorek method and 0.3 km with the Frazier method, the last one looked more accurate due to a short distance. With a larger distance like 100 km, we had 50 km with Wieczorek and 15 km with Frazier. Also using Frazier we keep the consistency in the method suggested to the audience for all types of distances.

With the suggestions made by John in the new best practices document, I think de difference between the methods is reduced.

**Comment by tucotuco** [comment]
Hi Ricardo, is this an observation, or do you suggest some change?

**Comment by RicardoOrtizG** [comment]
An observation based on the question you mention above to ask SiB Colombia, because as you say I think is a good idea to point the difference between these methods and make a recommendation based on the advantage of using each, of course taking into account the new improvements you made.

**Comment by tucotuco** [comment]
Clarified in 5736a02b37f21c68726bf00f679e73ae73ac68a7
