### ISSUE TITLE
Feature request: open term:dwc refs in new window

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-best-practices#20]
Transferring outstanding item from #16 👍 

> It would be good if all the links to the dwc:xxxxxxx references could spawn a new tab.

Usual syntax of adding a ^ at the end of the href doesn't work in this case.

**Comment by MattBlissett** [comment]
Why do we want this? It's generally considered most appropriate to leave links opening in the default way (e.g. https://www.w3.org/TR/WCAG20-TECHS/G200.html ), and this is what GBIF.org and most other long documents (Wikipedia articles, newspaper articles) do.

**Comment by kcopas** [comment]
Just parking the request here for future consideration. We've added new tabs to external references, which seems to have pleased @ArthurChapman for the way that it holds users' place in the guide—which is very much why I added them. 

For the DwC terms, I have to say, somehow I don't feel we need this. But let's let the thought simmer…

**Comment by ArthurChapman** [comment]
The issue here is that I use the left hand panel to move to a section (say §4) and then further on I click a link to dwc:xxxx - it takes me to the Darwin Terms etc as it should.  But by not sporning a new tab, when I hit the return - it does not take me back to where I was in the document (i.e. where the dwc:xxxx reference is) but back to §4 - I then have to work my way back through the document to find where I was.

**Comment by tucotuco** [comment]
I support Arthur's view on the user experience. It is frustration and a loss of time to have to keep finding one's place again while trying to get work done.
