### ISSUE TITLE
Coordinate systems refer to an isosceles trapezoid on the Earth’s surface and point

### ISSUE THREAD

**Issue by qgroom** [gbif/doc-georeferencing-best-practices#23]
Re: section 3.4.3 and the Georeferencing Calculator

When a coordinate is written on a specimen, such as Lat: 10.2° Long: −123.6° Datum: WGS84. The person is not referring to a point, but to a isosceles trapezoid that contains the location, of which the south-western corner is at exactly these coordinates. It is only by error that the latitude and longitude would be less than these values. Therefore, if you convert these coordinates into decimal coordinates is does not make sense to centre them around the south-western corner of the trapezoid, but the centre of it. The uncertainty should encompassed the whole of this trapezoid.
Indeed, a coordinate never actually refers to a point, it always refers to a trapezoid.

**Comment by tucotuco** [comment]
What you describe is just one case of how a grid works. It is not universal. As for capturing the uncertainty of the "trapezoid", the error due to coordinate precision does exactly that. I don't think there is any change to the document required based on this observation.

**Comment by ArthurChapman** [comment]
Agree with @tuco. What @qgroom is describing is only one type of coordinate - a geographic coordinate. Other types of coordinates may describe a square (equal area grids) e.g. UTM coordinates, a rectangle, etc. The methodologies as written should work for all types of grids - and you are correct in that a point never actually refers to just a point.

**Comment by qgroom** [comment]
Rectangles and squares are just types of isosceles trapezoid. There are other grid systems, for example, based on three-sided trapezoids, but I have never heard of such a grid being used for this purpose. The point is, that in the example I give you base the centre of the error radius around the south-western corner of the trapezoid, not the centre of it. Yet in the same documentation if someone specifically says they are using a grid you centre the error radius it around the centre. This is inconsistent. All coordinates refer to a grid square, whether someone says it is part of a grid or not.

**Comment by tucotuco** [comment]
@qgroom I think we consider separately two things that you are talking about. One is a specified grid system and the other is a de facto grid based on the precision of a set of geographic coordinates where a grid is not declared.

With the specified grid system we know what the coordinate refers to and we can construct both a geometry and a minimum point radius to contain it based on the rules of the grid and any other sources of uncertainty that might come into play. We would treat this as a Geographic feature only calculation, determining the corrected center based on the grid rules.

If we are given coordinates only without any further grid knowledge (your original example, because we reject the statement "the south-western corner is at exactly these coordinates" without being told explicitly that it is the case), we recommend that the calculation proceed as a coordinates only calculation where the precision is a contributing factor. We have to apply rules to the coordinates to infer a defensible precision unless the precision is given explicitly, and we do not move the coordinates, because we have no evidence that they should be moved and there is no universal rule about shifting aside from the mathematical rules of rounding, which we find to be the most plausible reason that the coordinate was expressed as it was from a generalization of the original, more precise location.
