### ISSUE TITLE
Possible error in table 5

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#26]
I think there is a mistake in table 5, for 30 miles based on the Wieczorek method the uncertainty must be 0.5 miles, in the table is documented like 5 miles. Or maybe I have not understood how I should calculate it.

**Comment by ArthurChapman** [comment]
Thanks @RicardoOrtizG the 5mi is correct - by saying 30 miles someone could mean anywhere from 25mi to 35mi (and not necessarily between 29.5 and 30.5) and thus being conservative 5mi is given as the recommended Uncertainty.

**Comment by ArthurChapman** [comment]
From @tucotuco 
@RicardoOrtizG is actually correct! "For distance measurements that are positive integer powers of 10, the precision should be ten to the next lower power. " 30 is 3 times a positive integer power of 10 (power 1), so the precision should be 10^0 or 1, so the uncertainty should be 0.5. This is one of the changes since Wieczorek 2004 because it was deemed excessive. The other examples in Table 5 (140 km, 200 mi, 2000 m) bear this out.

Very astute, Ricardo. Thanks for catching that.
