### ISSUE TITLE
3.4.7 Doubt about combined uncertainties

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#27]
I see that there is no example of combined uncertainty for the distance uncertainty and the uncertainty due to the shape of the named place in chapter 3.4.6 from the new best practice document. But I think there is a reference in 3.4.7 to use the same methods mentioned in Wieczorek 2004, but is not clear for me if still can be right to add (+) de results from different uncertainties associated with localities, to have a total uncertainty. For example: datum uncertainty + scale uncertainty + distance uncertainty+ uncertainty due to extention.

**Comment by RicardoOrtizG** [comment]
The link highlighted in the next image from the chapter 3.4.7,  is pointing to the glossary and not the chapter mentioned in the georeferencing calculator manual.

![image](https://user-images.githubusercontent.com/15789737/96927859-4ff73280-147d-11eb-905d-1370d9b044cf.png)

**Comment by ArthurChapman** [comment]
Thanks for picking that up - it will need to be corrected @kcopas  - this should point to §9 in the Bloom et al paper (i.e. https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/#understanding-uncertainty)

**Comment by tucotuco** [comment]
> I see that there is no example of combined uncertainty for the distance uncertainty and the uncertainty due to the shape of the named place in chapter 3.4.6 from the new best practice document. But I think there is a reference in 3.4.7 to use the same methods mentioned in Wieczorek 2004, but is not clear for me if still can be right to add (+) de results from different uncertainties associated with localities, to have a total uncertainty. For example: datum uncertainty + scale uncertainty + distance uncertainty+ uncertainty due to extention.

Hi @RicardoOrtizG, 
That paragraph is meant to be introductory to the concept of combining uncertainties in general, with references to the theoretical works where those considerations are discussed. I guess the message here is that the calculator takes care of all of that if you pick the right options and fill in the right values. I think an example here would be confusing, because it would be only one of the myriad possibilities based on locality type, data sources, etc. 

Can you think of a way to improve upon what we have here to both avoid confusion and satisfy the expectation you had?

**Comment by tucotuco** [comment]
@RicardoOrtizG is actually correct!  "For distance measurements that are positive integer powers of 10, the precision should be ten to the next lower power. " 30 is 3 times a positive integer power of 10 (power 1), so the precision should be 10^0 or 1, so the uncertainty should be 0.5.  This is one of the changes since Wieczorek 2004 because it was deemed excessive. The other examples in Table 5 (140 km, 200 mi, 2000 m) bear this out.

Very astute, Ricardo. Thanks for catching that.

**Comment by ArthurChapman** [comment]
@tucotuco The last comment refers to #26.  I have copied it there.

**Comment by tucotuco** [comment]
Right, thank you @ArthurChapman

**Comment by ArthurChapman** [comment]
§3.4.7 in Sentence "To understand how each source of uncertainty contributes to the net overall uncertainty, see Understanding Uncertainty Contributions in the Georeferencing Calculator Manual (Bloom et al. 2020)."  the Link for "Understanding Uncertainty  Contributions" should point to "https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/#understanding-uncertainty"  NOT to the Glossary as it does now

**Comment by kcopas** [comment]
Link corrected. However, leaving open since I'm uncertain whether other text changes are required.

**Comment by tucotuco** [comment]
Don't we have to push every change to avoid problems merging?

**Comment by kcopas** [comment]
You mean a release? If so, then no, not yet—we're still pre-release mode where changes are picked up on the gbif-uat domain.

However, to stay consistent, I should have made the change in the review-edits branch…

**Comment by tucotuco** [comment]
The latter is what I meant.

**Comment by tucotuco** [comment]
We think this is satisfactorily covered and the needed fix is also addressed. Closing.
