### ISSUE TITLE
Depth definition needs clarification

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-best-practices#52]
Right now it could be interpreted as a positive value for negative elevation. Make clearer that it is strictly meant as depth below the surface of water.

**Comment by laurarussell** [comment]
@tucotuco Can you confirm that this definition addresses your issue? I'm thinking this issue was never closed out. Or if it still needs revising, this is good time to do it as a release to address changes to Grid is imminent.

"depth
A measurement of the vertical distance below a [vertical datum](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#vertical-datum). In this document, we try to modify the term to signify the medium in which the measurement is made. Thus, "water depth" is the vertical distance below an air-water interface in a waterbody (ocean, lake, river, sinkhole, etc.). Compare [distance above surface](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#distance-above-surface). Depth is always a non-negative number."

**Comment by tucotuco** [comment]
This is already correct in the current version. Closing the issue.
